### ISSUE TITLE
Peer to peer code review 31/03/2023

### ISSUE THREAD

**Issue by sunga12** [iamsjunaid/My-Portfolio-Website-1#3]
- It would be a good idea to change your media query to 768px instead of 376px
- You can change the hamburger menu display property to `display: unset` to ensure it shows in the mobile version
- some of the buttons on the page, when hovered don't change the text color, kindly change the text color to white on hover
- The Buttons text is not aligned in the center
- Your logo in the desktop version is too close to the screen, kindly add a margin similar to the Figma design 
- When the button is disabled, you can change the background color to match the Figma design

**Comment by iamsjunaid** [comment]
Fixed the issues.
